<?php

namespace Database\Seeders;

use App\Models\PA;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ReportPASeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $reports = [
            [
                'street_name' => 'BINTARO IX BL JC 1 JL MALEO',
                'house_number' => 'None',
                'latitude' => '-6.286274',
                'longitude' => '106.760364',
            ],
            [
                'street_name' => 'BINTARO JAYA BL J2',
                'house_number' => 'None',
                'latitude' => '-6.2704926',
                'longitude' => '106.754028',
            ],
            [
                'street_name' => 'BINTARO JAYA BL Q2',
                'house_number' => 'None',
                'latitude' => '-6.2716923',
                'longitude' => '106.7534347',
            ],
            [
                'street_name' => 'BLOK C/29 KOMP IKP',
                'house_number' => 'None',
                'latitude' => '-6.2599174',
                'longitude' => '106.7709762',
            ],
            [
                'street_name' => 'BLOK C/39 KOMP IKP',
                'house_number' => 'None',
                'latitude' => '-6.2597289',
                'longitude' => '106.7714691',
            ],
            [
                'street_name' => 'JL MERIAM BLOK R No.2 0',
                'house_number' => 'None',
                'latitude' => '-6.2581268',
                'longitude' => '106.7563187',
            ],
            [
                'street_name' => 'JL MAWAR RT1/5 No.',
                'house_number' => 'None',
                'latitude' => '-6.2853469',
                'longitude' => '106.7613591',
            ],
            [
                'street_name' => 'JL MAWAR No. 20 D R',
                'house_number' => 'None',
                'latitude' => '-6.2856374',
                'longitude' => '106.7616048',
            ],
            [
                'street_name' => 'JL MAWAR RT 6/5 No.',
                'house_number' => 'None',
                'latitude' => '-6.285795',
                'longitude' => '106.7616121',
            ],
            [
                'street_name' => 'JL MAWAR No..27 TNH',
                'house_number' => 'None',
                'latitude' => '-6.2848964',
                'longitude' => '106.7623619',
            ],
            [
                'street_name' => 'JL MAWAR RT6/5 No..',
                'house_number' => 'None',
                'latitude' => '-6.2859072',
                'longitude' => '106.7625812',
            ],
            [
                'street_name' => 'JL MAWAR RT6/5 No.',
                'house_number' => 'None',
                'latitude' => '-6.2858193',
                'longitude' => '106.7630166',
            ],
            [
                'street_name' => 'JL KESEHATAN 4 No.7',
                'house_number' => 'None',
                'latitude' => '-6.26999333333333',
                'longitude' => '106.763023333333',
            ],
            [
                'street_name' => 'JL MAWAR No..7 BINT',
                'house_number' => 'None',
                'latitude' => '-6.28424',
                'longitude' => '106.763916666666',
            ],
            [
                'street_name' => 'JL MAWAR No. 22 RT',
                'house_number' => 'None',
                'latitude' => '-6.284605',
                'longitude' => '106.76535',
            ],
            [
                'street_name' => 'JL MADRASAH No. 2',
                'house_number' => 'None',
                'latitude' => '-6.2594998',
                'longitude' => '106.7702022',
            ],
            [
                'street_name' => 'KOMP PER IKPN No. C',
                'house_number' => 'None',
                'latitude' => '-6.2597291',
                'longitude' => '106.7714751',
            ],
            [
                'street_name' => 'JL BINTARO G/3A KE',
                'house_number' => 'None',
                'latitude' => '-6.2620352',
                'longitude' => '106.7722543',
            ],
            [
                'street_name' => 'GG RW RT1/1 No.8 PESANGGRAHAN 0',
                'house_number' => 'None',
                'latitude' => '-6.2495744',
                'longitude' => '106.7662478',
            ],
            [
                'street_name' => 'PESANGGRAHAN RT1/1 No..5 0',
                'house_number' => 'None',
                'latitude' => '-6.2497755',
                'longitude' => '106.7658622',
            ],
            [
                'street_name' => 'KP BINTARO RT3/1 No. 11  0',
                'house_number' => 'None',
                'latitude' => '-6.2498701',
                'longitude' => '106.7646155',
            ],
            [
                'street_name' => 'PASANGGRAHAN RT11/6 No.130',
                'house_number' => 'None',
                'latitude' => '-6.2499995',
                'longitude' => '106.7533833',
            ],
            [
                'street_name' => 'ULUJAMI RAYA RT 2/1 No. 26  0',
                'house_number' => 'None',
                'latitude' => '-6.2500058',
                'longitude' => '106.7652508',
            ],
            [
                'street_name' => 'JL ULUJAMI RY No.26 RT3/10',
                'house_number' => 'None',
                'latitude' => '-6.2502102',
                'longitude' => '106.76578',
            ],
            [
                'street_name' => 'GG RW ULUJAMI RY RT5/1 No.5 0',
                'house_number' => 'None',
                'latitude' => '-6.2502664',
                'longitude' => '106.7647703',
            ],
            [
                'street_name' => 'ULUJAMI RAYA No. 16',
                'house_number' => 'None',
                'latitude' => '-6.2505241',
                'longitude' => '106.764453',
            ],
            [
                'street_name' => 'JL D RT9/2 No.46 PETUKANGAN 0',
                'house_number' => 'None',
                'latitude' => '-6.2507757',
                'longitude' => '106.7532029',
            ],
            [
                'street_name' => 'JL MERBABU RT10/6 No.9 BINTARO0',
                'house_number' => 'None',
                'latitude' => '-6.2514533',
                'longitude' => '106.7559513',
            ],
            [
                'street_name' => 'ULUJAMI RT6/5 No.19 KEB LAMA0',
                'house_number' => 'None',
                'latitude' => '-6.2516918',
                'longitude' => '106.7644556',
            ],
            [
                'street_name' => 'TMN ALFA INDAH BL B8 No.80',
                'house_number' => 'None',
                'latitude' => '-6.25204',
                'longitude' => '106.75588',
            ],
            [
                'street_name' => 'JL PD INDAH RT9/6 No.27 PESANGR',
                'house_number' => 'None',
                'latitude' => '-6.2522643',
                'longitude' => '106.7555492',
            ],
            [
                'street_name' => 'JL FLAMBOYAN No.19 KOMP CPM 0',
                'house_number' => 'None',
                'latitude' => '-6.253802',
                'longitude' => '106.7556907',
            ],
            [
                'street_name' => 'KK DEPSOS GGXII No.',
                'house_number' => 'None',
                'latitude' => '-6.2627293560523',
                'longitude' => '106.76177021116',
            ],
            [
                'street_name' => 'PR METRO PERMATA II BL N1 No.39',
                'house_number' => 'None',
                'latitude' => '-6.2539456968294',
                'longitude' => '106.76026944554',
            ],
            [
                'street_name' => 'PR METRO PERMATA 2 BL D7 No.7 0',
                'house_number' => 'None',
                'latitude' => '-6.2539462193557',
                'longitude' => '106.75921207157',
            ],
            [
                'street_name' => 'KOMP MABES ABRI No.',
                'house_number' => 'None',
                'latitude' => '-6.2548091',
                'longitude' => '106.7677391',
            ],
            [
                'street_name' => 'JL RAYA ULUJAMI No. 140',
                'house_number' => 'None',
                'latitude' => '-6.2552836',
                'longitude' => '106.7633624',
            ],
            [
                'street_name' => 'KP BINTARO RT4/2 No.150',
                'house_number' => 'None',
                'latitude' => '-6.2555262',
                'longitude' => '106.7620529',
            ],
            [
                'street_name' => 'JL ULUJAMI RT4/1 No.16 BINTARO0',
                'house_number' => 'None',
                'latitude' => '-6.2558548424045',
                'longitude' => '106.76325615495',
            ],
            [
                'street_name' => 'JL SABAR No.50 RT9/4 PETUK SLT0',
                'house_number' => 'None',
                'latitude' => '-6.2559773',
                'longitude' => '106.7629483',
            ],
            [
                'street_name' => 'JL RC VETERAN No.23',
                'house_number' => 'None',
                'latitude' => '-6.2560173',
                'longitude' => '106.7688527',
            ],
            [
                'street_name' => 'RC VETERAN No..66',
                'house_number' => 'None',
                'latitude' => '-6.2562754',
                'longitude' => '106.7688372',
            ],
            [
                'street_name' => 'BINTARO GG H SAIRI RT1/3 No.170',
                'house_number' => 'None',
                'latitude' => '-6.2564536',
                'longitude' => '106.7668429',
            ],
            [
                'street_name' => 'KP DUREN RT 2/3 No.',
                'house_number' => 'None',
                'latitude' => '-6.2570475',
                'longitude' => '106.7598644',
            ],
            [
                'street_name' => 'JL THOMSON BLOK Q No.80',
                'house_number' => 'None',
                'latitude' => '-6.2576283',
                'longitude' => '106.7547539',
            ],
            [
                'street_name' => 'JL THOMSON BLOK Q No.70',
                'house_number' => 'None',
                'latitude' => '-6.257702',
                'longitude' => '106.7547191',
            ],
            [
                'street_name' => 'JL THOMSON BLOK Q No.30',
                'house_number' => 'None',
                'latitude' => '-6.2577293',
                'longitude' => '106.7555884',
            ],
            [
                'street_name' => 'JL THOMSON BLOK P No.70',
                'house_number' => 'None',
                'latitude' => '-6.2577527',
                'longitude' => '106.7551917',
            ],
            [
                'street_name' => 'JL MERIAM BLOK R No.3 0',
                'house_number' => 'None',
                'latitude' => '-6.2580149',
                'longitude' => '106.7545317',
            ],
            [
                'street_name' => 'JL MERIAM BLOK R No.6 0',
                'house_number' => 'None',
                'latitude' => '-6.2580675',
                'longitude' => '106.7550308',
            ],
            [
                'street_name' => 'JL SENAPAN BLOK L No.10',
                'house_number' => 'None',
                'latitude' => '-6.2580713',
                'longitude' => '106.755024',
            ],
            [
                'street_name' => 'BINTARO RT1/1 No..2',
                'house_number' => 'None',
                'latitude' => '-6.2581674',
                'longitude' => '106.7643126',
            ],
            [
                'street_name' => 'GG SINAN RT02/3 No.',
                'house_number' => 'None',
                'latitude' => '-6.2584344',
                'longitude' => '106.7598667',
            ],
            [
                'street_name' => 'BINTARO RT2/9 No.33',
                'house_number' => 'None',
                'latitude' => '-6.2584634',
                'longitude' => '106.7623611',
            ],
            [
                'street_name' => 'RC VETERAN No.23 KP',
                'house_number' => 'None',
                'latitude' => '-6.2585784',
                'longitude' => '106.7687415',
            ],
            [
                'street_name' => 'BINTARO RT5/1 No.27',
                'house_number' => 'None',
                'latitude' => '-6.2589673',
                'longitude' => '106.7626905',
            ],
            [
                'street_name' => 'JL PEMBANGUNAN No..',
                'house_number' => 'None',
                'latitude' => '-6.2592724',
                'longitude' => '106.7713446',
            ],
            [
                'street_name' => 'JL KODAM No.1A BINT',
                'house_number' => 'None',
                'latitude' => '-6.2594994',
                'longitude' => '106.7605452',
            ],
            [
                'street_name' => 'JL MADRASAH No. 53B',
                'house_number' => 'None',
                'latitude' => '-6.2595871',
                'longitude' => '106.7717248',
            ],
            [
                'street_name' => 'JL KP BINTARO RT4/4 No..31  0',
                'house_number' => 'None',
                'latitude' => '-6.2596136',
                'longitude' => '106.7563834',
            ],
            [
                'street_name' => 'JL INDOJATI No.9 RT',
                'house_number' => 'None',
                'latitude' => '-6.2597346',
                'longitude' => '106.767784',
            ],
            [
                'street_name' => 'JL BAKTI RT8/1 No.1',
                'house_number' => 'None',
                'latitude' => '-6.2598011',
                'longitude' => '106.7649241',
            ],
            [
                'street_name' => 'VETERAN RAYA No.35',
                'house_number' => 'None',
                'latitude' => '-6.2598577',
                'longitude' => '106.7678401',
            ],
            [
                'street_name' => 'JL IR.H JUANDA No..',
                'house_number' => 'None',
                'latitude' => '-6.2605361',
                'longitude' => '106.7693673',
            ],
            [
                'street_name' => 'JL BHAKTI RT5/1 No.',
                'house_number' => 'None',
                'latitude' => '-6.2609191',
                'longitude' => '106.7651032',
            ],
            [
                'street_name' => 'BINTARO BLOK C1 No.',
                'house_number' => 'None',
                'latitude' => '-6.2610342',
                'longitude' => '106.7673518',
            ],
            [
                'street_name' => 'JL BELIMBING No.22A KOMP KODAM0',
                'house_number' => 'None',
                'latitude' => '-6.261671',
                'longitude' => '106.7568938',
            ],
            [
                'street_name' => 'KOMP IKPN No.F 20A',
                'house_number' => 'None',
                'latitude' => '-6.2620352',
                'longitude' => '106.7722543',
            ],
            [
                'street_name' => 'JL GARUDA No. 4 BIN',
                'house_number' => 'None',
                'latitude' => '-6.2627785',
                'longitude' => '106.7667912',
            ],
            [
                'street_name' => 'JL DAHLIA No..3 BIN',
                'house_number' => 'None',
                'latitude' => '-6.2633646',
                'longitude' => '106.7663555',
            ],
            [
                'street_name' => 'DEPSOS No.15 RT9/1',
                'house_number' => 'None',
                'latitude' => '-6.2637605',
                'longitude' => '106.7656691',
            ],
            [
                'street_name' => 'JL KENANGA No. 42 B',
                'house_number' => 'None',
                'latitude' => '-6.2648807',
                'longitude' => '106.764658',
            ],
            [
                'street_name' => 'KESEHATAN RAYA No. 51E',
                'house_number' => 'None',
                'latitude' => '-6.2653707',
                'longitude' => '106.7653004',
            ],
            [
                'street_name' => 'BINTARO FB 11 No. 26A',
                'house_number' => 'None',
                'latitude' => '-6.2658397',
                'longitude' => '106.7584822',
            ],
            [
                'street_name' => 'JL RAYA BINTARO No.',
                'house_number' => 'None',
                'latitude' => '-6.2662034',
                'longitude' => '106.7638666',
            ],
            [
                'street_name' => 'JL KENANGA No..45 B',
                'house_number' => 'None',
                'latitude' => '-6.2662766',
                'longitude' => '106.7646598',
            ],
            [
                'street_name' => 'GG KENANGA No.28 RT',
                'house_number' => 'None',
                'latitude' => '-6.2665657',
                'longitude' => '106.764545',
            ],
            [
                'street_name' => 'Gg.BAKTI RT 5/2 No.',
                'house_number' => 'None',
                'latitude' => '-6.2671136',
                'longitude' => '106.7651886',
            ],
            [
                'street_name' => 'BINTARO JAYA D1 No.',
                'house_number' => 'None',
                'latitude' => '-6.2677773',
                'longitude' => '106.756789',
            ],
            [
                'street_name' => 'JL ANGGREK L No.15',
                'house_number' => 'None',
                'latitude' => '-6.2679189',
                'longitude' => '106.7684793',
            ],
            [
                'street_name' => 'BINTARO RT9/1 No.15',
                'house_number' => 'None',
                'latitude' => '-6.2684206',
                'longitude' => '106.754051',
            ],
            [
                'street_name' => 'JLN RC VETERAN No.2',
                'house_number' => 'None',
                'latitude' => '-6.2690311',
                'longitude' => '106.7640291',
            ],
            [
                'street_name' => 'JL MURAI III J2 No.',
                'house_number' => 'None',
                'latitude' => '-6.270098',
                'longitude' => '106.7543331',
            ],
            [
                'street_name' => 'JL KEMPO No.5 BINTA',
                'house_number' => 'None',
                'latitude' => '-6.2703966',
                'longitude' => '106.7633229',
            ],
            [
                'street_name' => 'KAV BLOK J4 No.9 KP',
                'house_number' => 'None',
                'latitude' => '-6.2704926',
                'longitude' => '106.754028',
            ],
            [
                'street_name' => 'JL MURAI III No.23',
                'house_number' => 'None',
                'latitude' => '-6.2709471',
                'longitude' => '106.7546446',
            ],
            [
                'street_name' => 'BINTARO JAYA JA No.',
                'house_number' => 'None',
                'latitude' => '-6.2710533',
                'longitude' => '106.7532371',
            ],
            [
                'street_name' => 'JL MERPATI II No..H',
                'house_number' => 'None',
                'latitude' => '-6.2710831',
                'longitude' => '106.7517667',
            ],
            [
                'street_name' => 'JL MURAI No. 1 RT1/',
                'house_number' => 'None',
                'latitude' => '-6.271629',
                'longitude' => '106.7550958',
            ],
            [
                'street_name' => 'KAV BLOK J4 No. 7 K',
                'house_number' => 'None',
                'latitude' => '-6.2716923',
                'longitude' => '106.7534347',
            ],
            [
                'street_name' => 'REMPOA RT12/01 No.3',
                'house_number' => 'None',
                'latitude' => '-6.2723245',
                'longitude' => '106.7579278',
            ],
            [
                'street_name' => 'JL DEPLU V No.26 RT',
                'house_number' => 'None',
                'latitude' => '-6.27245333333333',
                'longitude' => '106.768991666666',
            ],
            [
                'street_name' => 'JL.TMN BINTARO No..',
                'house_number' => 'None',
                'latitude' => '-6.2726697',
                'longitude' => '106.7591308',
            ],
            [
                'street_name' => 'BLOK F2 No. 14 BINT',
                'house_number' => 'None',
                'latitude' => '-6.2727092',
                'longitude' => '106.7549383',
            ],
            [
                'street_name' => 'JL RC VETERAN No.5',
                'house_number' => 'None',
                'latitude' => '-6.2729141',
                'longitude' => '106.7641187',
            ],
            [
                'street_name' => 'KOMP DEPSOS GGV No.',
                'house_number' => 'None',
                'latitude' => '-6.2732916',
                'longitude' => '106.7599104',
            ],
            [
                'street_name' => 'JL DEPLU RAYA No.14',
                'house_number' => 'None',
                'latitude' => '-6.27333166666666',
                'longitude' => '106.768883333333',
            ],
            [
                'street_name' => 'JL CEMPAKA IV No. 2',
                'house_number' => 'None',
                'latitude' => '-6.2735193',
                'longitude' => '106.7597817',
            ],
            [
                'street_name' => 'JL.MERAK IV M2 No..',
                'house_number' => 'None',
                'latitude' => '-6.2737184',
                'longitude' => '106.7539129',
            ],
            [
                'street_name' => 'H NAWIH No. 71',
                'house_number' => 'None',
                'latitude' => '-6.2738137',
                'longitude' => '106.7550633',
            ],
            [
                'street_name' => 'JL RC VETERAN No.1',
                'house_number' => 'None',
                'latitude' => '-6.2738828',
                'longitude' => '106.7621135',
            ],
            [
                'street_name' => 'CEMPAKA IV No.12 RT',
                'house_number' => 'None',
                'latitude' => '-6.2739974',
                'longitude' => '106.7592969',
            ],
            [
                'street_name' => 'JL PEDAGANGAN No. 1',
                'house_number' => 'None',
                'latitude' => '-6.2741251',
                'longitude' => '106.7635421',
            ],
            [
                'street_name' => 'TMN BINTARO No. A/2',
                'house_number' => 'None',
                'latitude' => '-6.2741745',
                'longitude' => '106.7549412',
            ],
            [
                'street_name' => 'PAL BATU RT2/3 No.1',
                'house_number' => 'None',
                'latitude' => '-6.2751701',
                'longitude' => '106.765183',
            ],
            [
                'street_name' => 'JL.CEMPK RY No..26',
                'house_number' => 'None',
                'latitude' => '-6.2753993',
                'longitude' => '106.7600655',
            ],
            [
                'street_name' => 'JL RY VETERAN No. 1',
                'house_number' => 'None',
                'latitude' => '-6.2764178',
                'longitude' => '106.7673042',
            ],
            [
                'street_name' => 'JL BAHAR RT 9/7 No.',
                'house_number' => 'None',
                'latitude' => '-6.2773151',
                'longitude' => '106.7653513',
            ],
            [
                'street_name' => 'REMPOA RT03/07 No.5',
                'house_number' => 'None',
                'latitude' => '-6.2777827',
                'longitude' => '106.76395',
            ],
            [
                'street_name' => 'GG PERINTIS No.1 RT',
                'house_number' => 'None',
                'latitude' => '-6.2782167',
                'longitude' => '106.7636945',
            ],
            [
                'street_name' => 'SAILAN II No. 22 RT.3RW.5',
                'house_number' => 'None',
                'latitude' => '-6.2792869',
                'longitude' => '106.7621941',
            ],
            [
                'street_name' => 'PR BUKIT BL H No.2',
                'house_number' => 'None',
                'latitude' => '-6.2798929',
                'longitude' => '106.7655078',
            ],
            [
                'street_name' => 'JL MAWAR II No.41 B',
                'house_number' => 'None',
                'latitude' => '-6.2815428',
                'longitude' => '106.7617582',
            ],
            [
                'street_name' => 'JL REMPOA RT3/5 No.',
                'house_number' => 'None',
                'latitude' => '-6.2822633',
                'longitude' => '106.7620744',
            ],
            [
                'street_name' => 'JL MAWAR RT1/14 No.',
                'house_number' => 'None',
                'latitude' => '-6.2843003',
                'longitude' => '106.7653746',
            ],
            [
                'street_name' => 'JL MAWAR RT9/5 No.1',
                'house_number' => 'None',
                'latitude' => '-6.2844795',
                'longitude' => '106.7639439',
            ],
            [
                'street_name' => 'JL MAWAR No. 20 RT0',
                'house_number' => 'None',
                'latitude' => '-6.284508',
                'longitude' => '106.7658396',
            ],
            [
                'street_name' => 'MAWAR No.5 RT04/13',
                'house_number' => 'None',
                'latitude' => '-6.2848239',
                'longitude' => '106.7639465',
            ],
            [
                'street_name' => 'GG BANTOL No. 14A B',
                'house_number' => 'None',
                'latitude' => '-6.2855034',
                'longitude' => '106.7655643',
            ],
            [
                'street_name' => 'BINTARO RT10/05 No.',
                'house_number' => 'None',
                'latitude' => '-6.285571',
                'longitude' => '106.7644538',
            ],
            [
                'street_name' => 'MAWAR No. 68',
                'house_number' => 'None',
                'latitude' => '-6.2862257',
                'longitude' => '106.7654901',
            ],
            [
                'street_name' => 'KOMP IKPN No.F 20A',
                'house_number' => 'None',
                'latitude' => '-6.2620352',
                'longitude' => '106.7722543',
            ],
            [
                'street_name' => 'JL MADRASAH No.53B',
                'house_number' => 'None',
                'latitude' => '-6.2595871',
                'longitude' => '106.7717248',
            ],
            [
                'street_name' => 'JL MADRASAH No.2',
                'house_number' => 'None',
                'latitude' => '-6.2594998',
                'longitude' => '106.7702022',
            ],
            [
                'street_name' => 'JL DEPLU RAYA No.1',
                'house_number' => 'None',
                'latitude' => '-6.27245333333333',
                'longitude' => '106.768991666666',
            ],
            [
                'street_name' => 'JL DEPLU RAYA No.14',
                'house_number' => 'None',
                'latitude' => '-6.27333166666666',
                'longitude' => '106.768883333333',
            ],
            [
                'street_name' => 'RC VETERAN NO.66',
                'house_number' => 'None',
                'latitude' => '-6.2562754',
                'longitude' => '106.7688372',
            ],
            [
                'street_name' => 'JL RC VETERAN No.16',
                'house_number' => 'None',
                'latitude' => '-6.2585784',
                'longitude' => '106.7687415',
            ],
            [
                'street_name' => 'VETERAN RAYA No.35',
                'house_number' => 'None',
                'latitude' => '-6.2598577',
                'longitude' => '106.7678401',
            ],
            [
                'street_name' => 'JL INDOJATI No.9 RT',
                'house_number' => 'None',
                'latitude' => '-6.2597346',
                'longitude' => '106.767784',
            ],
            [
                'street_name' => 'BINTARO GG H SAIRI RT1/3 No.170',
                'house_number' => 'None',
                'latitude' => '-6.2564536',
                'longitude' => '106.7668429',
            ],
            [
                'street_name' => 'JL GARUDA No.4 BIN',
                'house_number' => 'None',
                'latitude' => '-6.2627785',
                'longitude' => '106.7667912',
            ],
            [
                'street_name' => 'JL TERATAI No.2 TA',
                'house_number' => 'None',
                'latitude' => '-6.2633646',
                'longitude' => '106.7663555',
            ],
            [
                'street_name' => 'GG RW RT2/1 No.30 BINTARO0',
                'house_number' => 'None',
                'latitude' => '-6.2495744',
                'longitude' => '106.7662478',
            ],
            [
                'street_name' => 'PESANGGRAHAN RT1/1 NO.5 0',
                'house_number' => 'None',
                'latitude' => '-6.2497755',
                'longitude' => '106.7658622',
            ],
            [
                'street_name' => 'JL MAWAR No.20 RT0',
                'house_number' => 'None',
                'latitude' => '-6.284508',
                'longitude' => '106.7658396',
            ],
            [
                'street_name' => 'JL ULUJAMI RY No.26 RT3/10',
                'house_number' => 'None',
                'latitude' => '-6.2502102',
                'longitude' => '106.76578',
            ],
            [
                'street_name' => 'GG BANTOL No.14A B',
                'house_number' => 'None',
                'latitude' => '-6.2855034',
                'longitude' => '106.7655643',
            ],
            [
                'street_name' => 'PR BUKIT BL H No.2',
                'house_number' => 'None',
                'latitude' => '-6.2798929',
                'longitude' => '106.7655078',
            ],
            [
                'street_name' => 'JL MAWAR 2 No.15 RT',
                'house_number' => 'None',
                'latitude' => '-6.2862257',
                'longitude' => '106.7654901',
            ],
            [
                'street_name' => 'JL MAWAR No.22 RT',
                'house_number' => 'None',
                'latitude' => '-6.284605',
                'longitude' => '106.76535',
            ],
            [
                'street_name' => 'KESEHATAN RAYA No.51E',
                'house_number' => 'None',
                'latitude' => '-6.2653707',
                'longitude' => '106.7653004',
            ],
            [
                'street_name' => 'ULUJAMI RAYA RT 2/1 No.26  0',
                'house_number' => 'None',
                'latitude' => '-6.2500058',
                'longitude' => '106.7652508',
            ],
            [
                'street_name' => 'PAL BATU RT2/3 No.1',
                'house_number' => 'None',
                'latitude' => '-6.2751701',
                'longitude' => '106.765183',
            ],
            [
                'street_name' => 'GG RW ULUJAMI RY RT5/1 No.5 0',
                'house_number' => 'None',
                'latitude' => '-6.2502664',
                'longitude' => '106.7647703',
            ],
            [
                'street_name' => 'JL KENANGA NO.45 B',
                'house_number' => 'None',
                'latitude' => '-6.2662766',
                'longitude' => '106.7646598',
            ],
            [
                'street_name' => 'JL KENANGA No.42 B',
                'house_number' => 'None',
                'latitude' => '-6.2648807',
                'longitude' => '106.764658',
            ],
            [
                'street_name' => 'KP BINTARO RT3/1 No.11  0',
                'house_number' => 'None',
                'latitude' => '-6.2498701',
                'longitude' => '106.7646155',
            ],
            [
                'street_name' => 'GG KENANGA No.28 RT',
                'house_number' => 'None',
                'latitude' => '-6.2665657',
                'longitude' => '106.764545',
            ],
            [
                'street_name' => 'JL GURU SALIIN RT4/5 No.11  0',
                'house_number' => 'None',
                'latitude' => '-6.2516918',
                'longitude' => '106.7644556',
            ],
            [
                'street_name' => 'ULUJAMI RAYA No.16',
                'house_number' => 'None',
                'latitude' => '-6.2505241',
                'longitude' => '106.764453',
            ],
            [
                'street_name' => 'BINTARO RT1/1 NO.2',
                'house_number' => 'None',
                'latitude' => '-6.2581674',
                'longitude' => '106.7643126',
            ],
            [
                'street_name' => 'RS VETERAN NO. 1C',
                'house_number' => 'None',
                'latitude' => '-6.2729141',
                'longitude' => '106.7641187',
            ],
            [
                'street_name' => 'REMPOA RT03/07 No.5',
                'house_number' => 'None',
                'latitude' => '-6.2777827',
                'longitude' => '106.76395',
            ],
            [
                'street_name' => 'MAWAR No.5 RT04/13',
                'house_number' => 'None',
                'latitude' => '-6.2848239',
                'longitude' => '106.7639465',
            ],
            [
                'street_name' => 'JL MAWAR RT9/5 No.1',
                'house_number' => 'None',
                'latitude' => '-6.2844795',
                'longitude' => '106.7639439',
            ],
            [
                'street_name' => 'JL MAWAR NO.7 BINT',
                'house_number' => 'None',
                'latitude' => '-6.28424',
                'longitude' => '106.763916666666',
            ],
            [
                'street_name' => 'GG PERINTIS No.1 RT',
                'house_number' => 'None',
                'latitude' => '-6.2782167',
                'longitude' => '106.7636945',
            ],
            [
                'street_name' => 'RAYA ULUJAMI RT2/2 No.05A0',
                'house_number' => 'None',
                'latitude' => '-6.2552836',
                'longitude' => '106.7633624',
            ],
            [
                'street_name' => 'JL H SALIM No.17 R',
                'house_number' => 'None',
                'latitude' => '-6.2703966',
                'longitude' => '106.7633229',
            ],
            [
                'street_name' => 'JL ULUJAMI RT4/1 No.16 BINTARO0',
                'house_number' => 'None',
                'latitude' => '-6.2558548424045',
                'longitude' => '106.76325615495',
            ],
            [
                'street_name' => 'JL KESEHATAN 4 No.7',
                'house_number' => 'None',
                'latitude' => '-6.26999333333333',
                'longitude' => '106.763023333333',
            ],
            [
                'street_name' => 'JL SABAR II No.33 PETUK SELATAN',
                'house_number' => 'None',
                'latitude' => '-6.2559773',
                'longitude' => '106.7629483',
            ],
            [
                'street_name' => 'BINTARO RT5/1 No.27',
                'house_number' => 'None',
                'latitude' => '-6.2589673',
                'longitude' => '106.7626905',
            ],
            [
                'street_name' => 'JL MAWAR NO.27 TNH',
                'house_number' => 'None',
                'latitude' => '-6.2848964',
                'longitude' => '106.7623619',
            ],
            [
                'street_name' => 'BINTARO RT2/9 No.33',
                'house_number' => 'None',
                'latitude' => '-6.2584634',
                'longitude' => '106.7623611',
            ],
            [
                'street_name' => 'KP BINTARO RT4/2 No.150',
                'house_number' => 'None',
                'latitude' => '-6.2555262',
                'longitude' => '106.7620529',
            ],
            [
                'street_name' => 'JL MAWAR II No.41 B',
                'house_number' => 'None',
                'latitude' => '-6.2815428',
                'longitude' => '106.7617582',
            ],
            [
                'street_name' => 'JL MAWAR No.20 D R',
                'house_number' => 'None',
                'latitude' => '-6.2856374',
                'longitude' => '106.7616048',
            ],
            [
                'street_name' => 'JL KODAM No.1A BINT',
                'house_number' => 'None',
                'latitude' => '-6.2594994',
                'longitude' => '106.7605452',
            ],
            [
                'street_name' => 'PR METRO PERMATA II BL N1 No.39',
                'house_number' => 'None',
                'latitude' => '-6.2539456968294',
                'longitude' => '106.76026944554',
            ],
            [
                'street_name' => 'CEMPAKA IV No.12 RT',
                'house_number' => 'None',
                'latitude' => '-6.2739974',
                'longitude' => '106.7592969',
            ],
            [
                'street_name' => 'PR METRO PERMATA 2 BL D7 No.7 0',
                'house_number' => 'None',
                'latitude' => '-6.2539462193557',
                'longitude' => '106.75921207157',
            ],
            [
                'street_name' => 'BINTARO FB 11 No.26A',
                'house_number' => 'None',
                'latitude' => '-6.2658397',
                'longitude' => '106.7584822',
            ],
            [
                'street_name' => 'KP BULAK RT4/1 No.2',
                'house_number' => 'None',
                'latitude' => '-6.2723245',
                'longitude' => '106.7579278',
            ],
            [
                'street_name' => 'JL BELIMBING No.10B KOMP KODAM0',
                'house_number' => 'None',
                'latitude' => '-6.261671',
                'longitude' => '106.7568938',
            ],
            [
                'street_name' => 'JL KP BINTARO RT4/4 NO.31  0',
                'house_number' => 'None',
                'latitude' => '-6.2596136',
                'longitude' => '106.7563834',
            ],
            [
                'street_name' => 'JL MERIAM BLOK R No.2 0',
                'house_number' => 'None',
                'latitude' => '-6.2581268',
                'longitude' => '106.7563187',
            ],
            [
                'street_name' => 'JL SALAK RT4/7 No.1 PESANGG',
                'house_number' => 'None',
                'latitude' => '-6.2514533',
                'longitude' => '106.7559513',
            ],
            [
                'street_name' => 'TMN ALFA INDAH BL B8 No.80',
                'house_number' => 'None',
                'latitude' => '-6.25204',
                'longitude' => '106.75588',
            ],
            [
                'street_name' => 'JL CENEK II No.10',
                'house_number' => 'None',
                'latitude' => '-6.253802',
                'longitude' => '106.7556907',
            ],
            [
                'street_name' => 'JL THOMSON BLOK Q No.30',
                'house_number' => 'None',
                'latitude' => '-6.2577293',
                'longitude' => '106.7555884',
            ],
            [
                'street_name' => 'JL ANGGREK RT15/06 No.1 PESANGG',
                'house_number' => 'None',
                'latitude' => '-6.2522643',
                'longitude' => '106.7555492',
            ],
            [
                'street_name' => 'JL THOMSON BLOK P No.70',
                'house_number' => 'None',
                'latitude' => '-6.2577527',
                'longitude' => '106.7551917',
            ],
            [
                'street_name' => 'JL MURAI No.1 RT1/',
                'house_number' => 'None',
                'latitude' => '-6.271629',
                'longitude' => '106.7550958',
            ],
            [
                'street_name' => 'JL SWADAYA No.31 R',
                'house_number' => 'None',
                'latitude' => '-6.2738137',
                'longitude' => '106.7550633',
            ],
            [
                'street_name' => 'JL MERIAM BLOK R No.6 0',
                'house_number' => 'None',
                'latitude' => '-6.2580675',
                'longitude' => '106.7550308',
            ],
            [
                'street_name' => 'JL SENAPAN BLOK L No.10',
                'house_number' => 'None',
                'latitude' => '-6.2580713',
                'longitude' => '106.755024',
            ],
            [
                'street_name' => 'TMN BINTARO No.A/2',
                'house_number' => 'None',
                'latitude' => '-6.2741745',
                'longitude' => '106.7549412',
            ],
            [
                'street_name' => 'BLOK F2 No.14 BINT',
                'house_number' => 'None',
                'latitude' => '-6.2727092',
                'longitude' => '106.7549383',
            ],
            [
                'street_name' => 'JL THOMSON BLOK Q No.50',
                'house_number' => 'None',
                'latitude' => '-6.2576283',
                'longitude' => '106.7547539',
            ],
            [
                'street_name' => 'JL THOMSON BLOK Q No.70',
                'house_number' => 'None',
                'latitude' => '-6.257702',
                'longitude' => '106.7547191',
            ],
            [
                'street_name' => 'JL MURAI III No.23',
                'house_number' => 'None',
                'latitude' => '-6.2709471',
                'longitude' => '106.7546446',
            ],
            [
                'street_name' => 'JL MERIAM BLOK R No.3 0',
                'house_number' => 'None',
                'latitude' => '-6.2580149',
                'longitude' => '106.7545317',
            ],
            [
                'street_name' => 'KAV BLOK J4 No.8 KP',
                'house_number' => 'None',
                'latitude' => '-6.2704926',
                'longitude' => '106.754028',
            ],
            [
                'street_name' => 'MERPATI I Q2 No.12',
                'house_number' => 'None',
                'latitude' => '-6.2716923',
                'longitude' => '106.7534347',
            ],
            [
                'street_name' => 'JL PENERANGAN VI No.100',
                'house_number' => 'None',
                'latitude' => '-6.2499995',
                'longitude' => '106.7533833',
            ],
            [
                'street_name' => 'GG LURAH RT9/2 NO.15 CILEDUG 0',
                'house_number' => 'None',
                'latitude' => '-6.2507757',
                'longitude' => '106.7532029',
            ],
            [
                'street_name' => 'JL PER BUMI BINTARO B No.0 C/ RT.19 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2653313',
                'longitude' => '106.7556342',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.0 I B RT.0 RW. 0 ',
                'house_number' => 'None',
                'latitude' => '-6.2654015',
                'longitude' => '106.7556667',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.4 A B RT.0 RW. 0 ',
                'house_number' => 'None',
                'latitude' => '-6.2656521',
                'longitude' => '106.7556975',
            ],
            [
                'street_name' => 'JL PER BUMI BINTARO B No.0 F/1 RT.0 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2656536',
                'longitude' => '106.7535322',
            ],
            [
                'street_name' => 'JL PER BUMI BINTARO B No.0 /23 RT. RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2656541',
                'longitude' => '106.7552067',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.0 BL RT.0 RW. 20 ',
                'house_number' => 'None',
                'latitude' => '-6.2657014',
                'longitude' => '106.755569',
            ],
            [
                'street_name' => 'JL PER BUMI BINTARO B No.0 C/ RT.24 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2657062',
                'longitude' => '106.7551702',
            ],
            [
                'street_name' => 'JL KOMP BUMI BINTARO No.0 MAI RT.0 RW. 0 ',
                'house_number' => 'None',
                'latitude' => '-6.2657272',
                'longitude' => '106.7554899',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.4 BL RT.0 RW. 0 ',
                'house_number' => 'None',
                'latitude' => '-6.2657429',
                'longitude' => '106.7540792',
            ],
            [
                'street_name' => 'JL BINTARO PUSPITA IIA No.27  RT.0 RW. 0 BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.2658132',
                'longitude' => '106.7550003',
            ],
            [
                'street_name' => 'JL PR BUMI BINTARO BL No.0 B/2 RT.2 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2658248',
                'longitude' => '106.7555049',
            ],
            [
                'street_name' => 'JL PER BUMI BINTARO B No.0 B/ RT.23 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2658285',
                'longitude' => '106.7555035',
            ],
            [
                'street_name' => 'JL BTR PUSPITA 2 A/C No.31  RT. RW.  BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.2658391',
                'longitude' => '106.7548751',
            ],
            [
                'street_name' => 'JL BINTARO PUSPITA IIA BLK C No.29  RT. RW.  BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.2658477',
                'longitude' => '106.7549654',
            ],
            [
                'street_name' => 'JL BINTARO PUSPITA IIA No.30  RT.2 RW. 8 PESANGGRAH',
                'house_number' => 'None',
                'latitude' => '-6.2658478',
                'longitude' => '106.7549107',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.0 A B RT.0 RW. -3 ',
                'house_number' => 'None',
                'latitude' => '-6.2658576',
                'longitude' => '106.7548669',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.0 BL RT.0 RW. 9 ',
                'house_number' => 'None',
                'latitude' => '-6.2658601',
                'longitude' => '106.7538008',
            ],
            [
                'street_name' => 'JL BINTARO PUSPITA IV No.0  RT.0 RW. 0 BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.265865',
                'longitude' => '106.7540895',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.0 BL RT.0 RW. 15 ',
                'house_number' => 'None',
                'latitude' => '-6.2659141',
                'longitude' => '106.7541333',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.0 BL RT.0 RW. 16 ',
                'house_number' => 'None',
                'latitude' => '-6.265936',
                'longitude' => '106.754153',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.0 A/ RT.17 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2659407',
                'longitude' => '106.7541214',
            ],
            [
                'street_name' => 'JL BINTARO PUSPITA V BLOK FF No.11  RT.3 RW. 8 BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.2659686',
                'longitude' => '106.7533715',
            ],
            [
                'street_name' => 'JL BINTARO PUSPITA V BLOK FF No.9  RT.3 RW. 8 PESANGGRHN',
                'house_number' => 'None',
                'latitude' => '-6.2659939',
                'longitude' => '106.753639',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.0 BL RT.0 RW. 7 ',
                'house_number' => 'None',
                'latitude' => '-6.2661082',
                'longitude' => '106.7537465',
            ],
            [
                'street_name' => 'JL PER BUMI BINTARO B No.0 F/1 RT.2 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2661258',
                'longitude' => '106.7531497',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.4 BL RT.0 RW. 1 ',
                'house_number' => 'None',
                'latitude' => '-6.266126',
                'longitude' => '106.754426',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.0 A B RT.0 RW. 0 ',
                'house_number' => 'None',
                'latitude' => '-6.2661787',
                'longitude' => '106.7547848',
            ],
            [
                'street_name' => 'JL BINTARO MELATI II No.0 FF/ RT.15 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.26623',
                'longitude' => '106.7533253',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.0 BL RT.0 RW. 2 ',
                'house_number' => 'None',
                'latitude' => '-6.2662493',
                'longitude' => '106.7540107',
            ],
            [
                'street_name' => 'JL BINTARO PUSPITA V BLOK FF No.3  RT. RW.  PESANGGRAH',
                'house_number' => 'None',
                'latitude' => '-6.2663017',
                'longitude' => '106.7540341',
            ],
            [
                'street_name' => 'JL PUSPITA V FF No.4  RT.3 RW. 8 PSGRHN',
                'house_number' => 'None',
                'latitude' => '-6.2663072',
                'longitude' => '106.7539606',
            ],
            [
                'street_name' => 'JL BINTARO PUSPITA BL No.0 /2 RT. RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2663283',
                'longitude' => '106.7540408',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.0 A-2 RT.4 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2663404',
                'longitude' => '106.75404',
            ],
            [
                'street_name' => 'JL BINTARO PUSPITA V BLK FF No.1  RT.3 RW. 5 BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.2663662',
                'longitude' => '106.7540912',
            ],
            [
                'street_name' => 'JL JL BINTARO MELATI No.0 BL RT.0 RW. 17 ',
                'house_number' => 'None',
                'latitude' => '-6.2664397',
                'longitude' => '106.753421',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.4 BL RT.0 RW. 8 ',
                'house_number' => 'None',
                'latitude' => '-6.2664478',
                'longitude' => '106.7545282',
            ],
            [
                'street_name' => 'JL JL BINTARO MELATI No.0 BLK RT.0 RW. 1 ',
                'house_number' => 'None',
                'latitude' => '-6.2664696',
                'longitude' => '106.7533636',
            ],
            [
                'street_name' => 'JL JL BINTARO MELATI No.0 BLK RT.0 RW. 0 ',
                'house_number' => 'None',
                'latitude' => '-6.2665166',
                'longitude' => '106.7535243',
            ],
            [
                'street_name' => 'JL BINTARO MELATI II No.0 FF/ RT.14 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2665207',
                'longitude' => '106.7532675',
            ],
            [
                'street_name' => 'JL JL BINTARO MELATI No.0 FF RT.0 RW. 20 ',
                'house_number' => 'None',
                'latitude' => '-6.2665473',
                'longitude' => '106.75364',
            ],
            [
                'street_name' => 'JL PER BUMI BINTARO B No.0 FF RT.0 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2665806',
                'longitude' => '106.7535995',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.0 BL RT.0 RW. 0 ',
                'house_number' => 'None',
                'latitude' => '-6.2666381',
                'longitude' => '106.7542407',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.0 BL RT.0 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2666442',
                'longitude' => '106.7543709',
            ],
            [
                'street_name' => 'JL JL BINTARO MELATI No.0 BL RT.0 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2666539',
                'longitude' => '106.7553474',
            ],
            [
                'street_name' => 'JL JL BINTARO MELATI2 No.0 K F RT.0 RW. -2 ',
                'house_number' => 'None',
                'latitude' => '-6.2666644',
                'longitude' => '106.7538332',
            ],
            [
                'street_name' => 'JL BINTARO PUSPITA V BL R No.9  RT.4 RW. 8 PSGRAHAN',
                'house_number' => 'None',
                'latitude' => '-6.266799',
                'longitude' => '106.7546366',
            ],
            [
                'street_name' => 'JL JL BINTARO MELATI No.0 BLK RT.0 RW. 2 ',
                'house_number' => 'None',
                'latitude' => '-6.2669544',
                'longitude' => '106.7538652',
            ],
            [
                'street_name' => 'JL MELATI 2 BLOK S 1-2 No.0  RT. RW.  PESANGGRAH',
                'house_number' => 'None',
                'latitude' => '-6.2669547',
                'longitude' => '106.7538688',
            ],
            [
                'street_name' => 'JL JL B PUSPITA V A B No.0 /7 RT. RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2669955',
                'longitude' => '106.7542589',
            ],
            [
                'street_name' => 'JL JL.PUSPITA V R10 B No.0 B RT.0 RW. 0 ',
                'house_number' => 'None',
                'latitude' => '-6.2670017',
                'longitude' => '106.7546336',
            ],
            [
                'street_name' => 'JL BINTARO PUSPITA V No.0 A/3 RT.5 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2670038',
                'longitude' => '106.7546026',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.0 BL RT.0 RW. 11 ',
                'house_number' => 'None',
                'latitude' => '-6.2670073',
                'longitude' => '106.7541758',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.0 R/ RT.12 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2671861',
                'longitude' => '106.7544575',
            ],
            [
                'street_name' => 'JL RAYA BINTARO PUSPITA BLK R No.11  RT. RW.  BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.2672931',
                'longitude' => '106.7544684',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.0 A B RT.0 RW. -2 ',
                'house_number' => 'None',
                'latitude' => '-6.2674705',
                'longitude' => '106.7540219',
            ],
            [
                'street_name' => 'JL PER BUMI BINTARO B No.0 R/ RT.1 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2674707',
                'longitude' => '106.7538496',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.0 YA RT.0 RW. 0 ',
                'house_number' => 'None',
                'latitude' => '-6.267478',
                'longitude' => '106.7541489',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.0 AA RT.0 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2676348',
                'longitude' => '106.7538687',
            ],
            [
                'street_name' => 'JL JL BINTARO MELATI No.0 L A RT.0 RW. 2 ',
                'house_number' => 'None',
                'latitude' => '-6.2676891',
                'longitude' => '106.7535921',
            ],
            [
                'street_name' => 'JL JL BINTARO MELATI No.0 AA RT.0 RW. 1 ',
                'house_number' => 'None',
                'latitude' => '-6.2677001',
                'longitude' => '106.753549',
            ],
            [
                'street_name' => 'JL JL BINTARO MELATI No.0 BL RT.0 RW. 7 ',
                'house_number' => 'None',
                'latitude' => '-6.2677182',
                'longitude' => '106.7535683',
            ],
            [
                'street_name' => 'JL BINTARO MELATI IV BLK BB No.8  RT. RW.  BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.2677943',
                'longitude' => '106.7536068',
            ],
            [
                'street_name' => 'JL JL BINTARO MELATI No.0 BL RT.0 RW. 6 ',
                'house_number' => 'None',
                'latitude' => '-6.2678081',
                'longitude' => '106.7535634',
            ],
            [
                'street_name' => 'JL JL BINTARO MELATI No.0 BB5 RT. RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2678151',
                'longitude' => '106.7535124',
            ],
            [
                'street_name' => 'JL JL BINTARO MELATI No.0 L A RT.0 RW. 4 ',
                'house_number' => 'None',
                'latitude' => '-6.2678196',
                'longitude' => '106.7535785',
            ],
            [
                'street_name' => 'JL JL BINTARO MELATI No.0 BL RT.0 RW. 16 ',
                'house_number' => 'None',
                'latitude' => '-6.2678797',
                'longitude' => '106.7534358',
            ],
            [
                'street_name' => 'JL BINTARO MELATI III BLK BB No.19  RT.7 RW. 8 BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.2679383',
                'longitude' => '106.7530571',
            ],
            [
                'street_name' => 'JL JL BINTARO MELATI No.0 BL RT.0 RW. 4 ',
                'house_number' => 'None',
                'latitude' => '-6.2679477',
                'longitude' => '106.7533834',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.0 YA RT.0 RW. 6 ',
                'house_number' => 'None',
                'latitude' => '-6.2679552',
                'longitude' => '106.7537371',
            ],
            [
                'street_name' => 'JL BINTARO MELATI IV BLK AA No.18  RT.7 RW. 8 BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.2679806',
                'longitude' => '106.7533608',
            ],
            [
                'street_name' => 'JL JL BINTARO MELATI No.0 BB2 RT. RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2679878',
                'longitude' => '106.7533426',
            ],
            [
                'street_name' => 'JL BINTARO MELATI IV BLOK BB No.1 A RT. RW.  BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.2680001',
                'longitude' => '106.7533122',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.0 YA RT.0 RW. 5 ',
                'house_number' => 'None',
                'latitude' => '-6.2680035',
                'longitude' => '106.7536709',
            ],
            [
                'street_name' => 'JL JL BINTARO MELATI No.0 A B RT.0 RW. 0 ',
                'house_number' => 'None',
                'latitude' => '-6.2680037',
                'longitude' => '106.7528357',
            ],
            [
                'street_name' => 'JL BINTARO MELATI BL AA No.19 A RT.9 RW. 8 BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.2680072',
                'longitude' => '106.7533258',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.0 AA RT.-4 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2680383',
                'longitude' => '106.7537319',
            ],
            [
                'street_name' => 'JL RAYA BINTARO PUSPITA AA No.3  RT. RW.  BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.2680384',
                'longitude' => '106.7536602',
            ],
            [
                'street_name' => 'JL JL BINTARO PUPITA No.0 A A RT.0 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2681245',
                'longitude' => '106.7535498',
            ],
            [
                'street_name' => 'JL BINTARO MELATI IV BLOK BB No.1  RT.7 RW. 8 BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.2681266',
                'longitude' => '106.7532785',
            ],
            [
                'street_name' => 'JL BINTARO MELATI RAY No.0 J-5 RT. RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2681989',
                'longitude' => '106.7530309',
            ],
            [
                'street_name' => 'JL JL BINTARO PUSPITA No.0 BL RT.0 RW. -1 ',
                'house_number' => 'None',
                'latitude' => '-6.2682428',
                'longitude' => '106.7535262',
            ],
            [
                'street_name' => 'JL BINTARO MELATI RAYA BLOK JJ No.3  RT.8 RW. 8 PSANGRAHAN',
                'house_number' => 'None',
                'latitude' => '-6.2682507',
                'longitude' => '106.7531828',
            ],
            [
                'street_name' => 'JL PER BUMI BINTARO B No.0 AA RT.0 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2683777',
                'longitude' => '106.7532284',
            ],
            [
                'street_name' => 'JL GG MESJID RT1/1 KE No.0 INT RT.0 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2548091',
                'longitude' => '106.7677391',
            ],
            [
                'street_name' => 'JL MASJID ALMUFLIHUN No.30  RT.3 RW. 10 BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.2550761',
                'longitude' => '106.7674014',
            ],
            [
                'street_name' => 'KP BINTARO No.49  RT.4 RW. 10 BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.2554978998017',
                'longitude' => '106.76647346467',
            ],
            [
                'street_name' => 'JL BINTARO PONCOL No.0  RT.3 RW. 1 BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.2565385',
                'longitude' => '106.7638841',
            ],
            [
                'street_name' => 'JL JL BINTARO PERMAI No.0 A R RT.0 RW. 0 ',
                'house_number' => 'None',
                'latitude' => '-6.2568665',
                'longitude' => '106.764217',
            ],
            [
                'street_name' => 'JL BINTARO PERMAI RAYA No.19  RT.2 RW. 8 BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.2573017',
                'longitude' => '106.7631679',
            ],
            [
                'street_name' => 'JL BINTARO PERMAI III No.27  RT.1 RW. 4 BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.2575636',
                'longitude' => '106.7627639',
            ],
            [
                'street_name' => 'JL JL BINTARO PERMAI No.0 /9- RT.43 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.258377',
                'longitude' => '106.7629947',
            ],
            [
                'street_name' => 'JL BINTARO PERMAI III No.0  RT.4 RW. 1 BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.2584039',
                'longitude' => '106.7622382',
            ],
            [
                'street_name' => 'JL BINTARO PERMAI 3 G No.0 7A RT.0 RW. 0 ',
                'house_number' => 'None',
                'latitude' => '-6.258441',
                'longitude' => '106.7635843',
            ],
            [
                'street_name' => 'JL JL BINTARO PERMAI No.0 /17 RT.0 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2584436',
                'longitude' => '106.7631214',
            ],
            [
                'street_name' => 'JL BINTARO PERMAI III No.35  RT.2 RW. 9 BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.2584634',
                'longitude' => '106.7623611',
            ],
            [
                'street_name' => 'JL PESANGGRAHAN RT01/ No.02 BIN RT.0 RW. 0 ',
                'house_number' => 'None',
                'latitude' => '-6.2587311',
                'longitude' => '106.762355',
            ],
            [
                'street_name' => 'JL BINTARO RT5/1 NO27 No.  RT. RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2589673',
                'longitude' => '106.7626905',
            ],
            [
                'street_name' => 'JL BINTARO PERMAI III No.0  RT.5 RW. 1 BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.2627278',
                'longitude' => '106.7562749',
            ],
            [
                'street_name' => 'JL JL BINTARO MELATI No.0 A J RT.0 RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2653137',
                'longitude' => '106.7554399',
            ],
            [
                'street_name' => 'JL JL BINTARO MELATI No.0 BL RT.0 RW. 3 ',
                'house_number' => 'None',
                'latitude' => '-6.2653684',
                'longitude' => '106.7541554',
            ],
            [
                'street_name' => 'JL BINTARO PUSPITA III BLK  GB No.8  RT.1 RW. 8 BINTARO',
                'house_number' => 'None',
                'latitude' => '-6.2654423',
                'longitude' => '106.7543388',
            ],
            [
                'street_name' => 'JL JL BINTARO MELATI No.0 A F RT.0 RW. 0 ',
                'house_number' => 'None',
                'latitude' => '-6.2658891290533',
                'longitude' => '106.75331119448',
            ],
            [
                'street_name' => 'JL JL BINTARO MELATI No.0 AA- RT.15 RW. 0 ',
                'house_number' => 'None',
                'latitude' => '-6.2679019',
                'longitude' => '106.7534877',
            ],
            [
                'street_name' => 'JL PR BUMI BINTARO BL No.0 /1 RT. RW.  ',
                'house_number' => 'None',
                'latitude' => '-6.2684639916278',
                'longitude' => '106.7533544451',
            ],
        ];

        foreach ($reports as $report) {
            PA::create($report);
        }    
    }
}
